#!/bin/sh
set -e

CHOICE=$(
  cat ~/.bashscripts/fuzzel-emojis.txt \
    | fuzzel -d
)

[ -z "$CHOICE" ] && exit 0

# Extract only the emoji (first column)
EMOJI=$(echo "$CHOICE" | awk '{print $1}')

# Copy emoji to clipboard
echo -n "$EMOJI" | wl-copy

