#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
  selected=$1
else
  selected=$("$(dirname "$0")/sessionizer-select-project")
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename -- "$selected" | sed 's/[^[:alnum:]_-]/_/g')
# avoid dangerous names like 'bash' or 'nvim'
sanitised_name="_$selected_name"
tmux_running=$(pgrep -x tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s "$sanitised_name" -c "$selected"
    exit 0
fi

if ! tmux has-session -t="$sanitised_name" 2>/dev/null; then
    tmux new-session -d -s "$sanitised_name" -n "nvim" -c "$selected" "zsh -c 'nvim .'"
    tmux select-window -t "$sanitised_name:nvim"
fi
tmux switch-client -t "$sanitised_name"
